{
  parserClass="com.github.tghnx1.cobolplugin.parser.CobolParser"
  psiPackage="com.github.tghnx1.cobolplugin.psi"
  psiImplPackage="com.github.tghnx1.cobolplugin.psi.impl"
  elementTypeHolderClass="com.github.tghnx1.cobolplugin.psi.CobolTypes"
  elementTypeClass="com.github.tghnx1.cobolplugin.psi.CobolElementType"
  tokenTypeClass="com.github.tghnx1.cobolplugin.psi.CobolTokenType"

  tokens = [
    IDENTIFIER
    NUMBER
    STRING_LITERAL
    EQUALS
    DOT
    LPAREN
    RPAREN
  ]

}


cobolFile ::= item*

item ::= IDENTIFIER
        | NUMBER
        | DOT
        | EQUALS
        | STRING_LITERAL
        | LPAREN
        | RPAREN
